<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class FilesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('files')->delete();
        
        \DB::table('files')->insert(array (
            0 => 
            array (
                'created_at' => '2021-12-01 00:00:00',
                'file_name' => 'Struktur Organisasi',
                'file_name_en' => 'Organizational Structure',
                'file_path' => 'images/files/6331066401f4a.pdf',
                'file_year' => '2021',
                'id' => 1,
                'image' => '',
                'sequence' => 1,
                'status' => 'active',
                'subcategory_id' => 1,
                'updated_at' => '2022-10-10 03:13:02',
            ),
            1 => 
            array (
                'created_at' => '2021-10-04 00:00:00',
                'file_name' => 'Dewan Direksi',
                'file_name_en' => 'Board of Directors',
                'file_path' => 'images/files/6331081ae3998.pdf',
                'file_year' => '2021',
                'id' => 2,
                'image' => '',
                'sequence' => 1,
                'status' => 'active',
                'subcategory_id' => 2,
                'updated_at' => '2022-10-10 03:14:02',
            ),
            2 => 
            array (
                'created_at' => '2021-10-04 00:00:00',
                'file_name' => 'Dewan Komisaris',
                'file_name_en' => 'Board of Commissioners',
                'file_path' => 'images/files/6331084b52d46.pdf',
                'file_year' => '2021',
                'id' => 3,
                'image' => '',
                'sequence' => 2,
                'status' => 'active',
                'subcategory_id' => 2,
                'updated_at' => '2022-10-10 03:14:10',
            ),
            3 => 
            array (
                'created_at' => '2021-10-07 00:00:00',
                'file_name' => 'Komite Audit',
                'file_name_en' => 'Audit Committee',
                'file_path' => 'images/files/63310919686ab.pdf',
                'file_year' => '2021',
                'id' => 4,
                'image' => '',
                'sequence' => 1,
                'status' => 'active',
                'subcategory_id' => 3,
                'updated_at' => '2022-10-10 03:13:20',
            ),
            4 => 
            array (
                'created_at' => '2021-10-07 00:00:00',
                'file_name' => 'Komite Nominasi dan Remunerasi',
                'file_name_en' => 'Nomination and Remuneration Committee',
                'file_path' => 'images/files/6331093586315.pdf',
                'file_year' => '2021',
                'id' => 5,
                'image' => '',
                'sequence' => 3,
                'status' => 'active',
                'subcategory_id' => 3,
                'updated_at' => '2022-10-10 03:13:31',
            ),
            5 => 
            array (
                'created_at' => '2021-10-07 00:00:00',
                'file_name' => 'Piagam Komite Audit',
                'file_name_en' => 'Audit Committee Charter',
                'file_path' => 'images/files/6331094e48947.pdf',
                'file_year' => '2021',
                'id' => 6,
                'image' => '',
                'sequence' => 2,
                'status' => 'active',
                'subcategory_id' => 3,
                'updated_at' => '2022-10-10 03:13:39',
            ),
            6 => 
            array (
                'created_at' => '2022-04-21 00:00:00',
                'file_name' => 'Piagam Audit Internal',
                'file_name_en' => 'Internal Audit Charter',
                'file_path' => 'images/files/6331099529b3f.pdf',
                'file_year' => '2022',
                'id' => 7,
                'image' => '',
                'sequence' => 1,
                'status' => 'active',
                'subcategory_id' => 4,
                'updated_at' => '2022-10-10 03:12:54',
            ),
            7 => 
            array (
                'created_at' => '2021-10-07 00:00:00',
                'file_name' => 'Sektretaris Perusahaan',
                'file_name_en' => 'Corporate Secretary',
                'file_path' => 'images/files/63310a1f41cdc.pdf',
                'file_year' => '2021',
                'id' => 8,
                'image' => '',
                'sequence' => 1,
                'status' => 'active',
                'subcategory_id' => 5,
                'updated_at' => '2022-10-10 03:13:46',
            ),
            8 => 
            array (
                'created_at' => '2021-11-01 00:00:00',
                'file_name' => 'Surat Keterangan Pembagian Tugas dan Wewenang',
                'file_name_en' => 'Certificate of Division of Duties and Authorities',
                'file_path' => 'images/files/63310a66523e7.pdf',
                'file_year' => '2021',
                'id' => 9,
                'image' => '',
                'sequence' => 1,
                'status' => 'active',
                'subcategory_id' => 6,
                'updated_at' => '2022-10-10 03:13:12',
            ),
            9 => 
            array (
                'created_at' => '2021-10-28 00:00:00',
                'file_name' => 'Visi, Misi, dan Tata Nilai Perusahaan',
                'file_name_en' => 'Vision, Mission, and Corporate Values',
                'file_path' => 'images/files/63310dc2c3618.pdf',
                'file_year' => '2021',
                'id' => 10,
                'image' => '',
                'sequence' => 1,
                'status' => 'active',
                'subcategory_id' => 7,
                'updated_at' => '2022-10-10 03:15:40',
            ),
            10 => 
            array (
                'created_at' => '2022-09-26 00:00:00',
                'file_name' => 'Laporan Terkait Tata Kelola',
                'file_name_en' => 'Governance Related Reports',
                'file_path' => 'images/files/63310df94a6dc.pdf',
                'file_year' => '2022',
                'id' => 11,
                'image' => '',
                'sequence' => 1,
                'status' => 'active',
                'subcategory_id' => 8,
                'updated_at' => '2022-10-10 03:14:38',
            ),
            11 => 
            array (
                'created_at' => '2022-05-30 00:00:00',
                'file_name' => 'Laporan Keberlanjutan 2021',
                'file_name_en' => 'Sustainability Report 2021',
                'file_path' => 'images/files/633a8112adc59.pdf',
                'file_year' => '2022',
                'id' => 12,
                'image' => '',
                'sequence' => 1,
                'status' => 'active',
                'subcategory_id' => 9,
                'updated_at' => '2022-10-10 03:19:32',
            ),
            12 => 
            array (
                'created_at' => '2022-09-26 00:00:00',
                'file_name' => 'Lembaga Terkait',
                'file_name_en' => 'Supporting Institutions',
                'file_path' => 'images/files/63310e7b4a5b4.pdf',
                'file_year' => '2022',
                'id' => 13,
                'image' => '',
                'sequence' => 1,
                'status' => 'active',
                'subcategory_id' => 12,
                'updated_at' => '2022-10-10 03:15:32',
            ),
            13 => 
            array (
                'created_at' => '2021-10-04 00:00:00',
            'file_name' => 'Akta Anggaran Dasar No. 7 (Penawaran Saham Perdana / IPO)',
            'file_name_en' => 'Deed of Articles of Association No. 7 (Initial Public Offering / IPO)',
                'file_path' => 'images/files/63310f34992c8.pdf',
                'file_year' => '2021',
                'id' => 14,
                'image' => '',
                'sequence' => 1,
                'status' => 'active',
                'subcategory_id' => 13,
                'updated_at' => '2022-10-10 03:09:54',
            ),
            14 => 
            array (
                'created_at' => '2022-06-22 00:00:00',
                'file_name' => 'ASLC - AGM - Final_POA from Shareholders 2022',
                'file_name_en' => 'ASLC - AGM - Final_POA from Shareholders 2022',
                'file_path' => 'images/files/63310fca8a981.pdf',
                'file_year' => '2022',
                'id' => 15,
                'image' => '',
                'sequence' => 1,
                'status' => 'active',
                'subcategory_id' => 15,
                'updated_at' => '2022-10-10 03:09:36',
            ),
            15 => 
            array (
                'created_at' => '2022-06-22 00:00:00',
                'file_name' => 'ASLC - AGM - Final_Summon of Shareholders',
                'file_name_en' => 'ASLC - AGM - Final_Summon of Shareholders',
                'file_path' => 'images/files/63310fe05a827.pdf',
                'file_year' => '2022',
                'id' => 16,
                'image' => '',
                'sequence' => 2,
                'status' => 'active',
                'subcategory_id' => 15,
                'updated_at' => '2022-10-10 03:09:43',
            ),
            16 => 
            array (
                'created_at' => '2022-09-26 00:00:00',
                'file_name' => 'ASLC - AGM - Final_Surat Pernyataan Deklarasi Kesehatan',
                'file_name_en' => 'ASLC - AGM - Final_POA ASLC - AGM - Final_Statement of Health Declaration of 2022',
                'file_path' => 'images/files/633110077b114.pdf',
                'file_year' => '2022',
                'id' => 17,
                'image' => '',
                'sequence' => 3,
                'status' => 'active',
                'subcategory_id' => 15,
                'updated_at' => '2022-10-10 03:09:22',
            ),
            17 => 
            array (
                'created_at' => '2022-09-26 00:00:00',
                'file_name' => 'Pengumuman RUPS Autopedia',
                'file_name_en' => 'Announcement of Autopedia GMS',
                'file_path' => 'images/files/633110336b3f2.pdf',
                'file_year' => '2022',
                'id' => 18,
                'image' => '',
                'sequence' => 4,
                'status' => 'active',
                'subcategory_id' => 15,
                'updated_at' => '2022-10-10 03:09:29',
            ),
            18 => 
            array (
                'created_at' => '2021-07-22 00:00:00',
                'file_name' => 'CSR',
                'file_name_en' => 'CSR',
                'file_path' => 'images/files/6331108e8cb71.pdf',
                'file_year' => '2021',
                'id' => 19,
                'image' => '',
                'sequence' => 1,
                'status' => 'active',
                'subcategory_id' => 17,
                'updated_at' => '2022-10-10 03:11:48',
            ),
            19 => 
            array (
                'created_at' => '2021-12-31 00:00:00',
                'file_name' => 'Laporan Tahunan Autopedia 2021',
                'file_name_en' => 'Annual Report Autopedia 2021',
                'file_path' => 'images/files/633111331b571.pdf',
                'file_year' => '2021',
                'id' => 20,
                'image' => 'images/files/633111331ee79.png',
                'sequence' => 1,
                'status' => 'active',
                'subcategory_id' => 18,
                'updated_at' => '2022-10-10 03:12:43',
            ),
            20 => 
            array (
                'created_at' => '2021-12-31 00:00:00',
                'file_name' => 'Laporan Keuangan Konsolidasi 2021',
                'file_name_en' => 'Consolidated Financial Statements 2021',
                'file_path' => 'images/files/6331120fc4dc1.pdf',
                'file_year' => '2021',
                'id' => 21,
                'image' => '',
                'sequence' => 1,
                'status' => 'active',
                'subcategory_id' => 19,
                'updated_at' => '2022-10-10 03:12:35',
            ),
            21 => 
            array (
                'created_at' => '2022-03-31 00:00:00',
                'file_name' => 'Laporan Keuangan Q1 2022',
                'file_name_en' => 'Financial Report Q1 2022',
                'file_path' => 'images/files/633112291a0f6.pdf',
                'file_year' => '2022',
                'id' => 22,
                'image' => '',
                'sequence' => 2,
                'status' => 'active',
                'subcategory_id' => 19,
                'updated_at' => '2022-10-10 03:12:26',
            ),
            22 => 
            array (
                'created_at' => '2022-06-30 00:00:00',
                'file_name' => 'Laporan Keuangan Q2 2022',
                'file_name_en' => 'Financial Report Q2 2022',
                'file_path' => 'images/files/63311244b53ec.pdf',
                'file_year' => '2022',
                'id' => 23,
                'image' => '',
                'sequence' => 3,
                'status' => 'active',
                'subcategory_id' => 19,
                'updated_at' => '2022-10-10 03:12:18',
            ),
            23 => 
            array (
                'created_at' => '2022-08-01 00:00:00',
                'file_name' => 'Keterbukaan Informasi Pendirian Anak Usaha',
                'file_name_en' => 'Disclosure of Information on the Establishment of Subsidiaries',
                'file_path' => 'images/files/6331129936a2a.pdf',
                'file_year' => '2022',
                'id' => 24,
                'image' => '',
                'sequence' => 1,
                'status' => 'active',
                'subcategory_id' => 20,
                'updated_at' => '2022-10-10 03:10:35',
            ),
            24 => 
            array (
                'created_at' => '2022-06-22 00:00:00',
                'file_name' => 'Pengumuman Rapat Umum Pemegang Saham Tahunan PT Autopedia Sukses Lestari Tbk',
                'file_name_en' => 'Announcement of the Annual General Meeting of Shareholders of PT Autopedia Sukses Lestari Tbk',
                'file_path' => 'images/files/633112aeb8c22.pdf',
                'file_year' => '2022',
                'id' => 25,
                'image' => '',
                'sequence' => 2,
                'status' => 'active',
                'subcategory_id' => 20,
                'updated_at' => '2022-10-10 03:10:45',
            ),
            25 => 
            array (
                'created_at' => '2022-06-22 00:00:00',
                'file_name' => 'Pengumuman Ringkasan Risalah RUPSLB',
                'file_name_en' => 'Announcement of Summary minutes of EGMS',
                'file_path' => 'images/files/633112c6cfe55.pdf',
                'file_year' => '2022',
                'id' => 26,
                'image' => '',
                'sequence' => 3,
                'status' => 'active',
                'subcategory_id' => 20,
                'updated_at' => '2022-10-10 03:10:56',
            ),
            26 => 
            array (
                'created_at' => '2022-06-22 00:00:00',
                'file_name' => 'Pengumuman Ringkasan Risalah RUPST',
                'file_name_en' => 'Announcement of Summary minutes of the AGMS',
                'file_path' => 'images/files/633112de5d7fb.pdf',
                'file_year' => '2022',
                'id' => 27,
                'image' => '',
                'sequence' => 4,
                'status' => 'active',
                'subcategory_id' => 20,
                'updated_at' => '2022-10-10 03:11:07',
            ),
            27 => 
            array (
                'created_at' => '2022-01-18 00:00:00',
                'file_name' => 'Prospektus Penawaran Umum',
                'file_name_en' => 'Public Offering Prospectus',
                'file_path' => 'images/files/633112fcd925b.pdf',
                'file_year' => '2022',
                'id' => 28,
                'image' => '',
                'sequence' => 5,
                'status' => 'active',
                'subcategory_id' => 20,
                'updated_at' => '2022-10-10 03:11:28',
            ),
            28 => 
            array (
                'created_at' => '2022-01-18 00:00:00',
                'file_name' => 'Prospektus Ringkas Penawaran Umum',
                'file_name_en' => 'Public Offering Brief Prospectus',
                'file_path' => 'images/files/633113220061d.pdf',
                'file_year' => '2022',
                'id' => 29,
                'image' => '',
                'sequence' => 6,
                'status' => 'active',
                'subcategory_id' => 20,
                'updated_at' => '2022-10-10 03:11:37',
            ),
            29 => 
            array (
                'created_at' => '2022-05-22 00:00:00',
                'file_name' => 'Surat Kuasa RUPST-LB',
                'file_name_en' => 'Power of Attorney AGMS-LB',
                'file_path' => 'images/files/6331133a3e91f.pdf',
                'file_year' => '2022',
                'id' => 30,
                'image' => '',
                'sequence' => 7,
                'status' => 'active',
                'subcategory_id' => 20,
                'updated_at' => '2022-10-10 03:11:18',
            ),
            30 => 
            array (
                'created_at' => '2021-12-31 00:00:00',
                'file_name' => 'Komposisi Pemegang Saham',
                'file_name_en' => 'Shareholder Composition',
                'file_path' => 'images/files/633f9d4e8d3bc.pdf',
                'file_year' => '2021',
                'id' => 31,
                'image' => '',
                'sequence' => 1,
                'status' => 'active',
                'subcategory_id' => 22,
                'updated_at' => '2022-10-10 03:11:56',
            ),
            31 => 
            array (
                'created_at' => '2021-12-31 00:00:00',
                'file_name' => 'Struktur Organisasi Group',
                'file_name_en' => 'Group Organizational Structure',
                'file_path' => 'images/files/633f9d144e8aa.pdf',
                'file_year' => '2021',
                'id' => 32,
                'image' => '',
                'sequence' => 2,
                'status' => 'active',
                'subcategory_id' => 22,
                'updated_at' => '2022-10-10 03:12:05',
            ),
            32 => 
            array (
                'created_at' => '2021-11-16 00:00:00',
                'file_name' => 'ASSA Trimegah IPO ASL - An Integrated Omni-Channel Auto Marketplace Giant',
                'file_name_en' => 'ASSA Trimegah IPO ASL - An Integrated Omni-Channel Auto Marketplace Giant',
                'file_path' => 'images/files/63314df777451.pdf',
                'file_year' => '2021',
                'id' => 33,
                'image' => '',
                'sequence' => 1,
                'status' => 'active',
                'subcategory_id' => 23,
                'updated_at' => '2022-10-10 03:10:29',
            ),
            33 => 
            array (
                'created_at' => '2022-06-28 00:00:00',
                'file_name' => 'Trimegah CF ASLC - Blue Sky Awaits',
                'file_name_en' => 'Trimegah CF ASLC - Blue Sky Awaits',
                'file_path' => 'images/files/63314e23d1f09.pdf',
                'file_year' => '2022',
                'id' => 34,
                'image' => '',
                'sequence' => 2,
                'status' => 'active',
                'subcategory_id' => 23,
                'updated_at' => '2022-10-10 03:10:02',
            ),
            34 => 
            array (
                'created_at' => '2022-02-15 00:00:00',
            'file_name' => 'ASLC - Digitalizing The Brick and Mortar Used Car Business (BRI Danareksa)',
            'file_name_en' => 'ASLC - Digitalizing The Brick and Mortar Used Car Business (BRI Danareksa)',
                'file_path' => 'images/files/63314e3b70ff2.pdf',
                'file_year' => '2022',
                'id' => 35,
                'image' => '',
                'sequence' => 3,
                'status' => 'active',
                'subcategory_id' => 23,
                'updated_at' => '2022-10-10 03:10:11',
            ),
            35 => 
            array (
                'created_at' => '2022-02-14 00:00:00',
            'file_name' => 'Indonesia Automotive Auction (Online Auction Giant)',
            'file_name_en' => 'Indonesia Automotive Auction (Online Auction Giant)',
                'file_path' => 'images/files/63314e547b053.pdf',
                'file_year' => '2022',
                'id' => 36,
                'image' => '',
                'sequence' => 4,
                'status' => 'active',
                'subcategory_id' => 23,
                'updated_at' => '2022-10-10 03:10:19',
            ),
            36 => 
            array (
                'created_at' => '2021-12-31 00:00:00',
                'file_name' => 'Struktur Organisasi',
                'file_name_en' => 'Organizational Structure',
                'file_path' => 'images/files/633ce30bbdbe5.pdf',
                'file_year' => '2021',
                'id' => 37,
                'image' => '',
                'sequence' => 1,
                'status' => 'active',
                'subcategory_id' => 24,
                'updated_at' => '2022-10-10 03:14:20',
            ),
            37 => 
            array (
                'created_at' => '2021-12-31 00:00:00',
                'file_name' => 'Struktur Korporasi',
                'file_name_en' => 'Corporate Structure',
                'file_path' => 'images/files/633ea42f795de.pdf',
                'file_year' => '2021',
                'id' => 38,
                'image' => '',
                'sequence' => 2,
                'status' => 'active',
                'subcategory_id' => 25,
                'updated_at' => '2022-10-10 03:14:30',
            ),
        ));
        
        
    }
}