<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class JobsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('jobs')->delete();
        
        \DB::table('jobs')->insert(array (
            0 => 
            array (
                'created_at' => '2022-09-23 03:24:11',
            'description_en' => '<div><b>Your main task in developing with us:</b></div><ul><li>Build and manage infrastructure, running on Google Cloud and Amazon Web Services</li><li>Install, configure, and manage supporting applications such as HAProxy, MySQL, Nginx, Jenkins, Consul, Rundeck, or other required applications</li><li>Deploy internal Applications with Ansible</li><li>Apply any custom script with Bash or Python if needed</li><li>Create and provide detailed documentation for each task</li><li>Work together with software engineers to deploy code regularly</li><li>Improve our server-wide monitoring tools</li><li>Optimize the process of creating and deploying our server code</li><li>Apply autoscaling techniques</li><li>Analyze, design, and evaluate automation scripts and systems</li><li>Researching new technologies that will improve efficiency and effectiveness</li><li>Deploy a highly scalable development environment</li></ul><div><b>Mandatory skills you must prepare:</b></div><ul><li>Min 2 years experience (DevOps / Sysadmin / System engineer) with 1 year experience focused on cloud hosted commercial facing environment</li><li>Powerful script with Bash, Python</li><li>Powerful with Orchestration like Kubernetes</li><li>Experience with Cloud Platform: GCP</li><li>Experience with NoSQL DB such as MongoDB, ElasticSearch, MySQL</li><li>Powerful with automatic configuration management tools: Ansible</li><li>Experience with Containerization Concepts like Docker</li><li>Strong communication skills</li></ul>',
                'description_in' => '<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. A cras semper auctor neque. Neque vitae tempus quam pellentesque. Eu facilisis sed odio morbi quis. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. Et malesuada fames ac turpis egestas.&nbsp;A scelerisque purus semper eget duis at tellus at urna. Nisi quis eleifend quam adipiscing vitae. Imperdiet dui accumsan sit amet nulla. Nam libero justo laoreet sit amet cursus sit amet. Dui ut ornare lectus sit amet est placerat. Venenatis cras sed felis eget velit. Vestibulum lectus mauris ultrices eros in cursus turpis. Auctor eu augue ut lectus arcu bibendum at varius vel. Eu ultrices vitae auctor eu augue ut. Morbi tempus iaculis urna id volutpat lacus laoreet non curabitur. Ut ornare lectus sit amet est placerat in egestas erat. Euismod lacinia at quis risus. Et malesuada fames ac turpis egestas integer eget aliquet. Viverra orci sagittis eu volutpat odio facilisis mauris.</div><div><br>At augue eget arcu dictum varius duis at consectetur. Magna eget est lorem ipsum dolor sit amet consectetur. Eget nunc scelerisque viverra mauris in aliquam sem. Turpis cursus in hac habitasse platea dictumst. Amet massa vitae tortor condimentum lacinia quis. Id venenatis a condimentum vitae sapien pellentesque. Fringilla urna porttitor rhoncus dolor purus non enim. Massa enim nec dui nunc mattis enim ut tellus elementum. Molestie at elementum eu facilisis sed. Sem nulla pharetra diam sit amet nisl suscipit. Dui sapien eget mi proin. Ut placerat orci nulla pellentesque dignissim enim sit amet. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Tellus orci ac auctor augue mauris augue neque gravida. Sit amet nisl purus in mollis.</div>',
                'id' => 1,
                'job_type' => 'Pro-Hire',
                'location' => 'Caroline',
                'name' => 'DevOps Engineer',
                'slug' => 'devops-engineer-frcwSEOiOrIgGfTo',
                'status' => 'active',
                'updated_at' => '2022-10-03 01:21:07',
            ),
            1 => 
            array (
                'created_at' => '2022-09-23 03:27:34',
                'description_en' => '<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. A cras semper auctor neque. Neque vitae tempus quam pellentesque. Eu facilisis sed odio morbi quis. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. Et malesuada fames ac turpis egestas.A scelerisque purus semper eget duis at tellus at urna. Nisi quis eleifend quam adipiscing vitae. Imperdiet dui accumsan sit amet nulla. Nam libero justo laoreet sit amet cursus sit amet. Dui ut ornare lectus sit amet est placerat. Venenatis cras sed felis eget velit. Vestibulum lectus mauris ultrices eros in cursus turpis. Auctor eu augue ut lectus arcu bibendum at varius vel. Eu ultrices vitae auctor eu augue ut. Morbi tempus iaculis urna id volutpat lacus laoreet non curabitur. Ut ornare lectus sit amet est placerat in egestas erat. Euismod lacinia at quis risus. Et malesuada fames ac turpis egestas integer eget aliquet. Viverra orci sagittis eu volutpat odio facilisis mauris.</div><div><br>At augue eget arcu dictum varius duis at consectetur. Magna eget est lorem ipsum dolor sit amet consectetur. Eget nunc scelerisque viverra mauris in aliquam sem. Turpis cursus in hac habitasse platea dictumst. Amet massa vitae tortor condimentum lacinia quis. Id venenatis a condimentum vitae sapien pellentesque. Fringilla urna porttitor rhoncus dolor purus non enim. Massa enim nec dui nunc mattis enim ut tellus elementum. Molestie at elementum eu facilisis sed. Sem nulla pharetra diam sit amet nisl suscipit. Dui sapien eget mi proin. Ut placerat orci nulla pellentesque dignissim enim sit amet. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Tellus orci ac auctor augue mauris augue neque gravida. Sit amet nisl purus in mollis.</div>',
                'description_in' => '<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. A cras semper auctor neque. Neque vitae tempus quam pellentesque. Eu facilisis sed odio morbi quis. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. Et malesuada fames ac turpis egestas.A scelerisque purus semper eget duis at tellus at urna. Nisi quis eleifend quam adipiscing vitae. Imperdiet dui accumsan sit amet nulla. Nam libero justo laoreet sit amet cursus sit amet. Dui ut ornare lectus sit amet est placerat. Venenatis cras sed felis eget velit. Vestibulum lectus mauris ultrices eros in cursus turpis. Auctor eu augue ut lectus arcu bibendum at varius vel. Eu ultrices vitae auctor eu augue ut. Morbi tempus iaculis urna id volutpat lacus laoreet non curabitur. Ut ornare lectus sit amet est placerat in egestas erat. Euismod lacinia at quis risus. Et malesuada fames ac turpis egestas integer eget aliquet. Viverra orci sagittis eu volutpat odio facilisis mauris.</div><div><br>At augue eget arcu dictum varius duis at consectetur. Magna eget est lorem ipsum dolor sit amet consectetur. Eget nunc scelerisque viverra mauris in aliquam sem. Turpis cursus in hac habitasse platea dictumst. Amet massa vitae tortor condimentum lacinia quis. Id venenatis a condimentum vitae sapien pellentesque. Fringilla urna porttitor rhoncus dolor purus non enim. Massa enim nec dui nunc mattis enim ut tellus elementum. Molestie at elementum eu facilisis sed. Sem nulla pharetra diam sit amet nisl suscipit. Dui sapien eget mi proin. Ut placerat orci nulla pellentesque dignissim enim sit amet. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Tellus orci ac auctor augue mauris augue neque gravida. Sit amet nisl purus in mollis.</div>',
                'id' => 2,
                'job_type' => 'Pro-Hire',
                'location' => 'Cartalog',
                'name' => 'Senior Product Engineer',
                'slug' => 'senior-product-engineer-9h5OiIG0yUTNpbNT',
                'status' => 'active',
                'updated_at' => '2022-10-03 01:20:41',
            ),
            2 => 
            array (
                'created_at' => '2022-09-23 03:28:05',
                'description_en' => '<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. A cras semper auctor neque. Neque vitae tempus quam pellentesque. Eu facilisis sed odio morbi quis. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. Et malesuada fames ac turpis egestas.A scelerisque purus semper eget duis at tellus at urna. Nisi quis eleifend quam adipiscing vitae. Imperdiet dui accumsan sit amet nulla. Nam libero justo laoreet sit amet cursus sit amet. Dui ut ornare lectus sit amet est placerat. Venenatis cras sed felis eget velit. Vestibulum lectus mauris ultrices eros in cursus turpis. Auctor eu augue ut lectus arcu bibendum at varius vel. Eu ultrices vitae auctor eu augue ut. Morbi tempus iaculis urna id volutpat lacus laoreet non curabitur. Ut ornare lectus sit amet est placerat in egestas erat. Euismod lacinia at quis risus. Et malesuada fames ac turpis egestas integer eget aliquet. Viverra orci sagittis eu volutpat odio facilisis mauris.</div><div><br>At augue eget arcu dictum varius duis at consectetur. Magna eget est lorem ipsum dolor sit amet consectetur. Eget nunc scelerisque viverra mauris in aliquam sem. Turpis cursus in hac habitasse platea dictumst. Amet massa vitae tortor condimentum lacinia quis. Id venenatis a condimentum vitae sapien pellentesque. Fringilla urna porttitor rhoncus dolor purus non enim. Massa enim nec dui nunc mattis enim ut tellus elementum. Molestie at elementum eu facilisis sed. Sem nulla pharetra diam sit amet nisl suscipit. Dui sapien eget mi proin. Ut placerat orci nulla pellentesque dignissim enim sit amet. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Tellus orci ac auctor augue mauris augue neque gravida. Sit amet nisl purus in mollis.</div>',
                'description_in' => '<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. A cras semper auctor neque. Neque vitae tempus quam pellentesque. Eu facilisis sed odio morbi quis. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. Et malesuada fames ac turpis egestas.A scelerisque purus semper eget duis at tellus at urna. Nisi quis eleifend quam adipiscing vitae. Imperdiet dui accumsan sit amet nulla. Nam libero justo laoreet sit amet cursus sit amet. Dui ut ornare lectus sit amet est placerat. Venenatis cras sed felis eget velit. Vestibulum lectus mauris ultrices eros in cursus turpis. Auctor eu augue ut lectus arcu bibendum at varius vel. Eu ultrices vitae auctor eu augue ut. Morbi tempus iaculis urna id volutpat lacus laoreet non curabitur. Ut ornare lectus sit amet est placerat in egestas erat. Euismod lacinia at quis risus. Et malesuada fames ac turpis egestas integer eget aliquet. Viverra orci sagittis eu volutpat odio facilisis mauris.</div><div><br>At augue eget arcu dictum varius duis at consectetur. Magna eget est lorem ipsum dolor sit amet consectetur. Eget nunc scelerisque viverra mauris in aliquam sem. Turpis cursus in hac habitasse platea dictumst. Amet massa vitae tortor condimentum lacinia quis. Id venenatis a condimentum vitae sapien pellentesque. Fringilla urna porttitor rhoncus dolor purus non enim. Massa enim nec dui nunc mattis enim ut tellus elementum. Molestie at elementum eu facilisis sed. Sem nulla pharetra diam sit amet nisl suscipit. Dui sapien eget mi proin. Ut placerat orci nulla pellentesque dignissim enim sit amet. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Tellus orci ac auctor augue mauris augue neque gravida. Sit amet nisl purus in mollis.</div>',
                'id' => 3,
                'job_type' => 'Internship',
                'location' => 'JBA Indonesia',
                'name' => 'Back-End Developer Intern',
                'slug' => 'back-end-developer-intern-Ykny97buJh1jYap6',
                'status' => 'active',
                'updated_at' => '2022-10-03 01:20:29',
            ),
            3 => 
            array (
                'created_at' => '2022-09-23 03:29:32',
                'description_en' => '<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. A cras semper auctor neque. Neque vitae tempus quam pellentesque. Eu facilisis sed odio morbi quis. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. Et malesuada fames ac turpis egestas.<span style="font-family: Nunito, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 1rem;">A scelerisque purus semper eget duis at tellus at urna. Nisi quis eleifend quam adipiscing vitae. Imperdiet dui accumsan sit amet nulla. Nam libero justo laoreet sit amet cursus sit amet. Dui ut ornare lectus sit amet est placerat. Venenatis cras sed felis eget velit. Vestibulum lectus mauris ultrices eros in cursus turpis. Auctor eu augue ut lectus arcu bibendum at varius vel. Eu ultrices vitae auctor eu augue ut. Morbi tempus iaculis urna id volutpat lacus laoreet non curabitur. Ut ornare lectus sit amet est placerat in egestas erat. Euismod lacinia at quis risus. Et malesuada fames ac turpis egestas integer eget aliquet. Viverra orci sagittis eu volutpat odio facilisis mauris.</span></div><div><span style="font-family: Nunito, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 1rem;"><br></span><span style="font-family: Nunito, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 1rem;">At augue eget arcu dictum varius duis at consectetur. Magna eget est lorem ipsum dolor sit amet consectetur. Eget nunc scelerisque viverra mauris in aliquam sem. Turpis cursus in hac habitasse platea dictumst. Amet massa vitae tortor condimentum lacinia quis. Id venenatis a condimentum vitae sapien pellentesque. Fringilla urna porttitor rhoncus dolor purus non enim. Massa enim nec dui nunc mattis enim ut tellus elementum. Molestie at elementum eu facilisis sed. Sem nulla pharetra diam sit amet nisl suscipit. Dui sapien eget mi proin. Ut placerat orci nulla pellentesque dignissim enim sit amet. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Tellus orci ac auctor augue mauris augue neque gravida. Sit amet nisl purus in mollis.</span></div>',
                'description_in' => '<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. A cras semper auctor neque. Neque vitae tempus quam pellentesque. Eu facilisis sed odio morbi quis. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. Et malesuada fames ac turpis egestas.A scelerisque purus semper eget duis at tellus at urna. Nisi quis eleifend quam adipiscing vitae. Imperdiet dui accumsan sit amet nulla. Nam libero justo laoreet sit amet cursus sit amet. Dui ut ornare lectus sit amet est placerat. Venenatis cras sed felis eget velit. Vestibulum lectus mauris ultrices eros in cursus turpis. Auctor eu augue ut lectus arcu bibendum at varius vel. Eu ultrices vitae auctor eu augue ut. Morbi tempus iaculis urna id volutpat lacus laoreet non curabitur. Ut ornare lectus sit amet est placerat in egestas erat. Euismod lacinia at quis risus. Et malesuada fames ac turpis egestas integer eget aliquet. Viverra orci sagittis eu volutpat odio facilisis mauris.</div><div><br>At augue eget arcu dictum varius duis at consectetur. Magna eget est lorem ipsum dolor sit amet consectetur. Eget nunc scelerisque viverra mauris in aliquam sem. Turpis cursus in hac habitasse platea dictumst. Amet massa vitae tortor condimentum lacinia quis. Id venenatis a condimentum vitae sapien pellentesque. Fringilla urna porttitor rhoncus dolor purus non enim. Massa enim nec dui nunc mattis enim ut tellus elementum. Molestie at elementum eu facilisis sed. Sem nulla pharetra diam sit amet nisl suscipit. Dui sapien eget mi proin. Ut placerat orci nulla pellentesque dignissim enim sit amet. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Tellus orci ac auctor augue mauris augue neque gravida. Sit amet nisl purus in mollis.</div>',
                'id' => 4,
                'job_type' => 'Internship',
                'location' => 'JBA Indonesia',
                'name' => 'Front-End Developer Intern',
                'slug' => 'front-end-developer-intern-Iq9w8DEfy07pGmc6',
                'status' => 'active',
                'updated_at' => '2022-10-03 01:20:14',
            ),
            4 => 
            array (
                'created_at' => '2022-09-23 03:30:26',
                'description_en' => '<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. A cras semper auctor neque. Neque vitae tempus quam pellentesque. Eu facilisis sed odio morbi quis. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. Et malesuada fames ac turpis egestas.A scelerisque purus semper eget duis at tellus at urna. Nisi quis eleifend quam adipiscing vitae. Imperdiet dui accumsan sit amet nulla. Nam libero justo laoreet sit amet cursus sit amet. Dui ut ornare lectus sit amet est placerat. Venenatis cras sed felis eget velit. Vestibulum lectus mauris ultrices eros in cursus turpis. Auctor eu augue ut lectus arcu bibendum at varius vel. Eu ultrices vitae auctor eu augue ut. Morbi tempus iaculis urna id volutpat lacus laoreet non curabitur. Ut ornare lectus sit amet est placerat in egestas erat. Euismod lacinia at quis risus. Et malesuada fames ac turpis egestas integer eget aliquet. Viverra orci sagittis eu volutpat odio facilisis mauris.</div><div><br>At augue eget arcu dictum varius duis at consectetur. Magna eget est lorem ipsum dolor sit amet consectetur. Eget nunc scelerisque viverra mauris in aliquam sem. Turpis cursus in hac habitasse platea dictumst. Amet massa vitae tortor condimentum lacinia quis. Id venenatis a condimentum vitae sapien pellentesque. Fringilla urna porttitor rhoncus dolor purus non enim. Massa enim nec dui nunc mattis enim ut tellus elementum. Molestie at elementum eu facilisis sed. Sem nulla pharetra diam sit amet nisl suscipit. Dui sapien eget mi proin. Ut placerat orci nulla pellentesque dignissim enim sit amet. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Tellus orci ac auctor augue mauris augue neque gravida. Sit amet nisl purus in mollis.</div>',
                'description_in' => '<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. A cras semper auctor neque. Neque vitae tempus quam pellentesque. Eu facilisis sed odio morbi quis. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. Et malesuada fames ac turpis egestas.A scelerisque purus semper eget duis at tellus at urna. Nisi quis eleifend quam adipiscing vitae. Imperdiet dui accumsan sit amet nulla. Nam libero justo laoreet sit amet cursus sit amet. Dui ut ornare lectus sit amet est placerat. Venenatis cras sed felis eget velit. Vestibulum lectus mauris ultrices eros in cursus turpis. Auctor eu augue ut lectus arcu bibendum at varius vel. Eu ultrices vitae auctor eu augue ut. Morbi tempus iaculis urna id volutpat lacus laoreet non curabitur. Ut ornare lectus sit amet est placerat in egestas erat. Euismod lacinia at quis risus. Et malesuada fames ac turpis egestas integer eget aliquet. Viverra orci sagittis eu volutpat odio facilisis mauris.</div><div><br>At augue eget arcu dictum varius duis at consectetur. Magna eget est lorem ipsum dolor sit amet consectetur. Eget nunc scelerisque viverra mauris in aliquam sem. Turpis cursus in hac habitasse platea dictumst. Amet massa vitae tortor condimentum lacinia quis. Id venenatis a condimentum vitae sapien pellentesque. Fringilla urna porttitor rhoncus dolor purus non enim. Massa enim nec dui nunc mattis enim ut tellus elementum. Molestie at elementum eu facilisis sed. Sem nulla pharetra diam sit amet nisl suscipit. Dui sapien eget mi proin. Ut placerat orci nulla pellentesque dignissim enim sit amet. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Tellus orci ac auctor augue mauris augue neque gravida. Sit amet nisl purus in mollis.</div>',
                'id' => 5,
                'job_type' => 'Pro-Hire',
                'location' => 'Bursa Mobil Autopedia',
                'name' => 'Senior QA Engineer',
                'slug' => 'senior-qa-engineer-H6pffDUCxzxtZshp',
                'status' => 'active',
                'updated_at' => '2022-10-03 01:20:00',
            ),
            5 => 
            array (
                'created_at' => '2022-09-23 03:30:55',
            'description_en' => '<div>Your main task in developing with us:</div><ul><li>Build and manage infrastructure, running on Google Cloud and Amazon Web Services</li><li>Install, configure, and manage supporting applications such as HAProxy, MySQL, Nginx, Jenkins, Consul, Rundeck, or other required applications</li><li>Deploy internal Applications with Ansible</li><li>Apply any custom script with Bash or Python if needed</li><li>Create and provide detailed documentation for each task</li><li>Work together with software engineers to deploy code regularly</li><li>Improve our server-wide monitoring tools</li><li>Optimize the process of creating and deploying our server code</li><li>Apply autoscaling techniques</li><li>Analyze, design, and evaluate automation scripts and systems</li><li>Researching new technologies that will improve efficiency and effectiveness</li><li>Deploy a highly scalable development environment</li></ul><div>Mandatory skills you must prepare:</div><ul><li>Min 2 years experience (DevOps / Sysadmin / System engineer) with 1 year experience focused on cloud hosted commercial facing environment</li><li>Powerful script with Bash, Python</li><li>Powerful with Orchestration like Kubernetes</li><li>Experience with Cloud Platform: GCP</li><li>Experience with NoSQL DB such as MongoDB, ElasticSearch, MySQL</li><li>Powerful with automatic configuration management tools: Ansible</li><li>Experience with Containerization Concepts like Docker</li><li>Strong communication skills</li></ul>',
            'description_in' => '<div>Tugas utama Anda dalam berkembang bersama kami:</div><ul><li>Membangun dan mengelola infrastruktur, berjalan di Google Cloud dan Amazon Web Services</li><li>Instal, konfigurasikan, dan kelola aplikasi pendukung seperti HAProxy, MySQL, Nginx, Jenkins, Consul, Rundeck, atau aplikasi lain yang diperlukan</li><li>Menyebarkan Aplikasi internal dengan Ansible</li><li>Menerapkan skrip kustom apa pun dengan Bash atau Python jika diperlukan</li><li>Membuat dan memberikan dokumentasi terperinci untuk setiap tugas</li><li>Bekerja bersama dengan insinyur perangkat lunak untuk menyebarkan kode secara teratur</li><li>Tingkatkan alat pemantauan di seluruh server kami</li><li>Optimalkan proses pembuatan dan penyebaran kode server kami</li><li>Menerapkan teknik penskalaan otomatis</li><li>Menganalisis, merancang, dan mengevaluasi skrip dan sistem otomatisasi</li><li>Meneliti teknologi baru yang akan meningkatkan efisiensi dan efektivitas</li><li>Menerapkan lingkungan pengembangan yang sangat skalabel</li></ul><div>Skill wajib yang harus Anda siapkan:</div><ul><li>Pengalaman min 2 tahun (DevOps / Sysadmin / System engineer) dengan 1 tahun pengalaman yang berfokus pada lingkungan yang dihadapi komersial yang dihosting clou</li><li>Skrip yang kuat dengan Bash, Python</li><li>Kuat dengan Orkestrasi seperti Kubernetes</li><li>Pengalaman dengan Cloud Platform: GCP</li><li>Pengalaman dengan NoSQL DB seperti MongoDB, ElasticSearch, MySQL</li><li>Kuat dengan alat manajemen konfigurasi otomatis: Ansible</li><li>Pengalaman dengan Konsep Kontainerisasi seperti Docker</li><li>Keterampilan komunikasi yang kuat</li></ul>',
                'id' => 6,
                'job_type' => 'Pro-Hire',
                'location' => 'JBA Indonesia',
                'name' => 'Back-End Developer',
                'slug' => 'back-end-developer-nFx8uv7bZ5q2kYri',
                'status' => 'active',
                'updated_at' => '2022-10-03 01:19:30',
            ),
        ));
        
        
    }
}